version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: park-buddy-cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=park-buddy-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./backend/resources/init.cql:/docker-entrypoint-initdb.d/init.cql:ro
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  cassandra_data: 